version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt
    - goimports

linters:
  default: none
  enable:
    # Bugs
    - errcheck
    - govet
    - staticcheck  # includes gosimple and stylecheck
    - bodyclose
    - durationcheck
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - gosec
    - errorlint
    - makezero
    - nosprintfhostport
    - reassign

    # Performance
    - ineffassign
    - unconvert
    - copyloopvar
    - intrange

    # Unused code
    - unused

    # Style & consistency
    - revive
    - gocritic
    - misspell
    - dupword
    - godot
    - goprintffuncname
    - errname
    - predeclared
    - asciicheck
    - bidichk
    - usestdlibvars
    - whitespace

    # Maintainability
    - dupl
    - funlen
    - cyclop
    - gocyclo
    - gocognit

    # Additional quality checks (zero issues currently)
    - unparam           # Reports unused function parameters
    - forcetypeassert   # Finds forced type assertions
    - nakedret          # Checks naked returns in long functions
    - recvcheck         # Checks receiver type consistency
    - wastedassign      # Finds wasted assignments
    - thelper           # Checks t.Helper() in test helpers
    - perfsprint        # Suggests faster fmt alternatives
    - testableexamples  # Checks examples have expected output
    - nolintlint        # Reports ill-formed nolint directives
    - dogsled           # Checks for too many blank identifiers
    - gocheckcompilerdirectives  # Validates //go: directives
    - usetesting        # Reports deprecated testing funcs
    - mirror            # Checks bytes/strings usage patterns
    - nilnil            # Checks for nil error + nil value returns
    - modernize         # Suggests modern Go idioms (slices, maps, max/min)
    - goconst           # Finds repeated strings to make constants
    - prealloc          # Suggests pre-allocating slices

  settings:
    funlen:
      lines: 80
      statements: 50

    cyclop:
      # Inflection rules have many branches; 25 is reasonable for this domain
      max-complexity: 25

    gocyclo:
      # Inflection rules have many branches; 25 is reasonable for this domain
      min-complexity: 25

    gocognit:
      # Inflection rules are inherently complex with many branches
      min-complexity: 40

    dupl:
      threshold: 150

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - hugeParam  # Not relevant for this library

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id

    staticcheck:
      checks:
        - all
        - -ST1000  # Package comments not required
        - -ST1003  # Underscore in package name OK

  exclusions:
    # Test files can have longer functions and more complexity
    rules:
      - path: _test\.go
        linters:
          - funlen
          - cyclop
          - gocyclo
          - gocognit
          - dupl
          - dupword  # Test data legitimately contains repeated words
